name: Compile examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ekoeppen/gnat-cross-arm-eabi:community-2020
      volumes:
        - /home/runner/work:/build
    env:
      ADA_STM32_GD: /build/STM32_Generic_Ada_Drivers/STM32_Generic_Ada_Drivers/
    steps:
      - uses: actions/checkout@v2
      - name: Compile examples
        run: |
          ${ADA_STM32_GD}/examples/build.sh
